# Generated by Django 3.2.7 on 2021-10-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=dict)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=200, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('total', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('email', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=4)),
            ],
        ),
    ]
